### ISSUE TITLE
Hyper-parameters under low resource data setting

### ISSUE THREAD

**Issue by skpig** [RowitZou/DAMS#2]
Thanks for your remarkable work and detailed repo. I'm now focusing on dialogue summarization under the low resource data settings. Could you please help me reproduce the results in Figure 2 of your paper by providing hyper parameters (such as lr, training steps, warm up steps on fine tuning stage)?

**Comment by RowitZou** [comment]
Hi, there. The low-resource training settings are the same as that of full-data training. We practically use the same group of hyper-parameters for model training on different data halving ratios in Figure 2.

**Comment by skpig** [comment]
Thanks!
